name       : kildclient
version    : 3.2.0
release    : 4
source     :
    - https://cytranet.dl.sourceforge.net/project/kildclient/kildclient/3.2.0/kildclient-3.2.0.tar.gz : b1c2119cb208056e3bee9ee8f8b8ac1dcd8197d088b2341a90554e9fa9ac159d
license    : GPL-2.0
component  : network.clients
summary    : KildClient is a MUD client using the GTK+ toolkit.
description: |
    KildClient is a MUD client using the GTK+ toolkit.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtkspell3-3.0)
rundeps    :
    - perl-json
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
