name       : kildclient
version    : 3.1.0
release    : 1
source     :
    - https://cytranet.dl.sourceforge.net/project/kildclient/kildclient/3.1.0/kildclient-3.1.0.tar.gz : 14335590cf014ee2145ecd27c5e8ce4c44b253d27403f84a39f3e256083d19c2
license    : GPL-2.0
component  : network.clients
summary    : KildClient is a MUD client using the GTK+ toolkit.
description: |
    KildClient is a MUD client using the GTK+ toolkit.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtkspell3-3.0)
rundeps    :
    - perl-json
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
